### ISSUE TITLE
Error code 500 on /events (w/o trailing slash)

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#32]
## Problem
Getting internal server error on `/events` endpoint.

Traceback:
```py3tb
Traceback (most recent call last):
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 642, in respond
    self.get_resource(path_info)
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 760, in get_resource
    dispatch(path)
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 519, in __call__
    func = self.find_handler(path_info)
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 534, in find_handler
    config.environ = request.wsgi_environ
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/routes/__init__.py", line 22, in __setattr__
    self.load_wsgi_environ(value)
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/routes/__init__.py", line 51, in load_wsgi_environ
    result = mapper.routematch(path)
  File "/home/gtug2/gdg.org.ua/env/lib/python3.4/site-packages/routes/mapper.py", line 689, in routematch
    raise RoutesException('URL or environ must be provided')
routes.util.RoutesException: URL or environ must be provided
```

I suggest that the problem was caused with [these two lines](https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/src/GDGUkraine/controller.py#L172-L173), but I may be wrong.

## TODO
Investigate this bug and fix it

**Comment by webknjaz** [comment]
It's a bug of https://github.com/bbangert/routes
There's nothing we can do at the moment.

**Comment by webknjaz** [comment]
Should be fixed if this accepted https://github.com/bbangert/routes/pull/58

**Comment by webknjaz** [comment]
#83 will be temporary workaround for that

**Comment by webknjaz** [comment]
I've temporary set a commit-based requirement from github repo. TODO: change for version specificator once it's released.

**Comment by anxolerd** [comment]
@webknjaz is it done?
I cannot reproduce the bug anymore.

**Comment by webknjaz** [comment]
AFAIR, I've fixed this inside of `routes`

**Comment by webknjaz** [comment]
https://github.com/bbangert/routes/pull/58/files

**Comment by webknjaz** [comment]
https://github.com/GDG-Ukraine/gdg.org.ua/blob/edb0d0651c1345818e8863f9824b3fa64c7e0dcd/requirements/common.txt#L1
